### ISSUE TITLE
Issue with versions not triggering

### ISSUE THREAD

**Issue by Seraf** [nderjung/concourse-github-pr-comment-resource#1]
Hello !

Thanks for this resource, it's really really awesome!
As it's based on telia-oss one, is there any plan to propose it as a feature-patch instead of maintaining a fork ?

Also, it seems that I hit a bug today ...
On a PR, I added a comment that should have triggered my job .. the version has been seen by concourse, but it was not seen as a "new version".

![Screenshot from 2021-08-10 12-21-45](https://user-images.githubusercontent.com/393324/128851089-3de4155b-aa1c-4b3f-8560-b409990ce693.png)

Seeing the comment_id, you can guess that the comments in PR 5000 are more recent than the 4998's ones.
Once I pinned the 5000, it automatically ran the job.

Any idea why it hasn't been seen as a new version ?

**Comment by nderjung** [comment]
Hey @Seraf! Thanks for getting in contact :)

> As it's based on telia-oss one, is there any plan to propose it as a feature-patch instead of maintaining a fork ?

I originally looked into creating a fork which could be integrated, but after working with the fork it became clear that it was two separate types of resources.  The telia-oss version simply deals with new PRs in general, whereas this works with the comments and reviews of the PR.  Whilst you can trick this resource to looking at new PRs based on an initial new comment, it was still more work to create that fork.  Additionally, I believe the telia-oss version doesn't accept major changes when I was looking into it ):

> On a PR, I added a comment that should have triggered my job .. the version has been seen by concourse, but it was not seen as a "new version".

Are you setting the attribute `versions: every` for your get resource?

**Comment by Seraf** [comment]
Thanks for your fast answer !

I totally understand the reason, thanks for the explanation :)

About my issue, yes, I'm using `every`.

```yaml
            - get: github-pr-comment-e2e
              trigger: true
              version: every
```

What I don't get is why the versions of the PR 5000 appears below the 4998 one, as they are more recent, they should be on top AFAIU.
A colleague asked me why her comment wasn't triggering the pipeline. When I looked, I said that was weird, because her comment was below the 4998 one. So I asked her to do another comment, and this comment has been inserted "between" the 5000 and the 4998, so not seen as a new version.

**Comment by nderjung** [comment]
No worries! :) 

Oh i understand what's happening here: the comment ID is the latest version, not the PR. Because this resource plays with PR/Issue comments/reviews as the core resource, it sorts these by the latest: notice how the comment_id is sorted.  This is unlike the telia-oss where the PR is the core resource.

This means, that every latest version that comes in refers to the latest comment/review of the relevant PR/issue.

**Comment by Seraf** [comment]
That's what she did actually: *So I asked her to do another comment, and this comment has been inserted "between" the 5000 and the 4998, so not seen as a new version.*
That's the reason I decided to open an issue here, because I totally don't understand "why" ^^

**Comment by nderjung** [comment]
Oh I see. It must be an ordering thing coming from Github's API, since afaik the resource does not sort the versions before returning them.  I can look at making this change but I can't do it immediately :)

**Comment by Seraf** [comment]
Sure no worries ;)

Thanks for your support <3

**Comment by Seraf** [comment]
Hello :)
Is there something I can help with?
I'm not really familiar with Go, but maybe there's something on https://github.com/google/go-github/blob/master/github/pulls_comments.go#L53 that could help?

**Comment by nderjung** [comment]
Hola!

Yes likely this will work, you'll either have to modify all API request sequences to include this ordering:

https://github.com/nderjung/concourse-github-pr-comment-resource/blob/main/api/github.go#L127-L134

https://github.com/nderjung/concourse-github-pr-comment-resource/blob/main/api/github.go#L166-L171

https://github.com/nderjung/concourse-github-pr-comment-resource/blob/main/api/github.go#L187

but you can also do it manually by sorting the returning list of versions which is parsed by concourse:

https://github.com/nderjung/concourse-github-pr-comment-resource/blob/main/actions/check.go#L224

I'm more inclined on the latter method because the resource returns a mixed set of either PR/Issue comments or PR reviews. The only bit of additional logic that's required from the latter approach is to keep the timestamp to sort by it, because at the moment it's just returning the IDs of the comment/review and PR number.
